# Generated by Django 6.0.7 on 2026-07-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('license_number', models.CharField(blank=True, default='', max_length=128)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Platform base currency (see payments.Payment.currency).', max_digits=10, null=True)),
                ('cliniko_practitioner_id', models.CharField(blank=True, help_text='External Cliniko mapping — single nullable field (Docs/01, 07).', max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'practitioner profile',
                'verbose_name_plural': 'practitioner profiles',
            },
        ),
    ]
