# Generated by Django 6.0.7 on 2026-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMSSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_name', models.CharField(max_length=64)),
                ('sync_type', models.CharField(choices=[('pull_practitioners', 'Pull practitioners'), ('pull_availability', 'Pull availability'), ('push_appointment', 'Push appointment')], max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'PMS sync log',
                'verbose_name_plural': 'PMS sync logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
